package com.xinchao.entrytask.bus.model;

import java.util.Date;

public class ApplyUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_user.apply_weixin
     *
     * @mbggenerated
     */
    private String applyWeixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_user.apply_phone
     *
     * @mbggenerated
     */
    private String applyPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_user.apply_time
     *
     * @mbggenerated
     */
    private Date applyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_user
     *
     * @mbggenerated
     */
    public ApplyUser(Integer id, String applyWeixin, String applyPhone, Date applyTime) {
        this.id = id;
        this.applyWeixin = applyWeixin;
        this.applyPhone = applyPhone;
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_user
     *
     * @mbggenerated
     */
    public ApplyUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_user.id
     *
     * @return the value of apply_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_user.id
     *
     * @param id the value for apply_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_user.apply_weixin
     *
     * @return the value of apply_user.apply_weixin
     *
     * @mbggenerated
     */
    public String getApplyWeixin() {
        return applyWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_user.apply_weixin
     *
     * @param applyWeixin the value for apply_user.apply_weixin
     *
     * @mbggenerated
     */
    public void setApplyWeixin(String applyWeixin) {
        this.applyWeixin = applyWeixin == null ? null : applyWeixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_user.apply_phone
     *
     * @return the value of apply_user.apply_phone
     *
     * @mbggenerated
     */
    public String getApplyPhone() {
        return applyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_user.apply_phone
     *
     * @param applyPhone the value for apply_user.apply_phone
     *
     * @mbggenerated
     */
    public void setApplyPhone(String applyPhone) {
        this.applyPhone = applyPhone == null ? null : applyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_user.apply_time
     *
     * @return the value of apply_user.apply_time
     *
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_user.apply_time
     *
     * @param applyTime the value for apply_user.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }
}