package com.xinchao.entrytask.bus.model;

import java.math.BigDecimal;
import java.util.Date;

public class ApplyOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_order.apply_time
     *
     * @mbggenerated
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_order.complete_time
     *
     * @mbggenerated
     */
    private Date completeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_order.balance_bonus
     *
     * @mbggenerated
     */
    private BigDecimal balanceBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_order.bonus_url
     *
     * @mbggenerated
     */
    private String bonusUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_order.apply_user_id
     *
     * @mbggenerated
     */
    private Integer applyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_order.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_order.advantage_id
     *
     * @mbggenerated
     */
    private String advantageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_order.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_order.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_order
     *
     * @mbggenerated
     */
    public ApplyOrder(Integer id, Date applyTime, Date completeTime, BigDecimal balanceBonus, String bonusUrl, Integer applyUserId, Integer taskId, String advantageId, String status, String remarks) {
        this.id = id;
        this.applyTime = applyTime;
        this.completeTime = completeTime;
        this.balanceBonus = balanceBonus;
        this.bonusUrl = bonusUrl;
        this.applyUserId = applyUserId;
        this.taskId = taskId;
        this.advantageId = advantageId;
        this.status = status;
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_order
     *
     * @mbggenerated
     */
    public ApplyOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_order.id
     *
     * @return the value of apply_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_order.id
     *
     * @param id the value for apply_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_order.apply_time
     *
     * @return the value of apply_order.apply_time
     *
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_order.apply_time
     *
     * @param applyTime the value for apply_order.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_order.complete_time
     *
     * @return the value of apply_order.complete_time
     *
     * @mbggenerated
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_order.complete_time
     *
     * @param completeTime the value for apply_order.complete_time
     *
     * @mbggenerated
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_order.balance_bonus
     *
     * @return the value of apply_order.balance_bonus
     *
     * @mbggenerated
     */
    public BigDecimal getBalanceBonus() {
        return balanceBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_order.balance_bonus
     *
     * @param balanceBonus the value for apply_order.balance_bonus
     *
     * @mbggenerated
     */
    public void setBalanceBonus(BigDecimal balanceBonus) {
        this.balanceBonus = balanceBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_order.bonus_url
     *
     * @return the value of apply_order.bonus_url
     *
     * @mbggenerated
     */
    public String getBonusUrl() {
        return bonusUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_order.bonus_url
     *
     * @param bonusUrl the value for apply_order.bonus_url
     *
     * @mbggenerated
     */
    public void setBonusUrl(String bonusUrl) {
        this.bonusUrl = bonusUrl == null ? null : bonusUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_order.apply_user_id
     *
     * @return the value of apply_order.apply_user_id
     *
     * @mbggenerated
     */
    public Integer getApplyUserId() {
        return applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_order.apply_user_id
     *
     * @param applyUserId the value for apply_order.apply_user_id
     *
     * @mbggenerated
     */
    public void setApplyUserId(Integer applyUserId) {
        this.applyUserId = applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_order.task_id
     *
     * @return the value of apply_order.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_order.task_id
     *
     * @param taskId the value for apply_order.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_order.advantage_id
     *
     * @return the value of apply_order.advantage_id
     *
     * @mbggenerated
     */
    public String getAdvantageId() {
        return advantageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_order.advantage_id
     *
     * @param advantageId the value for apply_order.advantage_id
     *
     * @mbggenerated
     */
    public void setAdvantageId(String advantageId) {
        this.advantageId = advantageId == null ? null : advantageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_order.status
     *
     * @return the value of apply_order.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_order.status
     *
     * @param status the value for apply_order.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_order.remarks
     *
     * @return the value of apply_order.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_order.remarks
     *
     * @param remarks the value for apply_order.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}