package com.xinchao.entrytask.bus.model;

public class CodeHelpAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_help_answer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_help_answer.problem_id
     *
     * @mbggenerated
     */
    private Integer problemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_help_answer.answer
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_help_answer.enabled
     *
     * @mbggenerated
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_help_answer.sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help_answer
     *
     * @mbggenerated
     */
    public CodeHelpAnswer(Integer id, Integer problemId, String answer, String enabled, String sort) {
        this.id = id;
        this.problemId = problemId;
        this.answer = answer;
        this.enabled = enabled;
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help_answer
     *
     * @mbggenerated
     */
    public CodeHelpAnswer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_help_answer.id
     *
     * @return the value of code_help_answer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_help_answer.id
     *
     * @param id the value for code_help_answer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_help_answer.problem_id
     *
     * @return the value of code_help_answer.problem_id
     *
     * @mbggenerated
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_help_answer.problem_id
     *
     * @param problemId the value for code_help_answer.problem_id
     *
     * @mbggenerated
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_help_answer.answer
     *
     * @return the value of code_help_answer.answer
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_help_answer.answer
     *
     * @param answer the value for code_help_answer.answer
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_help_answer.enabled
     *
     * @return the value of code_help_answer.enabled
     *
     * @mbggenerated
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_help_answer.enabled
     *
     * @param enabled the value for code_help_answer.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_help_answer.sort
     *
     * @return the value of code_help_answer.sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_help_answer.sort
     *
     * @param sort the value for code_help_answer.sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }
}