package com.xinchao.entrytask.bus.model;

public class CodeHelp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_help.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_help.problem
     *
     * @mbggenerated
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_help.enabled
     *
     * @mbggenerated
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_help.sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help
     *
     * @mbggenerated
     */
    public CodeHelp(Integer id, String problem, String enabled, String sort) {
        this.id = id;
        this.problem = problem;
        this.enabled = enabled;
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help
     *
     * @mbggenerated
     */
    public CodeHelp() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_help.id
     *
     * @return the value of code_help.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_help.id
     *
     * @param id the value for code_help.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_help.problem
     *
     * @return the value of code_help.problem
     *
     * @mbggenerated
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_help.problem
     *
     * @param problem the value for code_help.problem
     *
     * @mbggenerated
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_help.enabled
     *
     * @return the value of code_help.enabled
     *
     * @mbggenerated
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_help.enabled
     *
     * @param enabled the value for code_help.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_help.sort
     *
     * @return the value of code_help.sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_help.sort
     *
     * @param sort the value for code_help.sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }
}