package com.xinchao.entrytask.bus.model;

import java.util.Date;

public class OptLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.supplier_id
     *
     * @mbggenerated
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.mode_name
     *
     * @mbggenerated
     */
    private String modeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.operation_type
     *
     * @mbggenerated
     */
    private Byte operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.operation_desc
     *
     * @mbggenerated
     */
    private String operationDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.operator_id
     *
     * @mbggenerated
     */
    private Integer operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbggenerated
     */
    public OptLog(Integer id, String supplierId, String modeName, Byte operationType, String operationDesc, Integer operatorId, Date createTime) {
        this.id = id;
        this.supplierId = supplierId;
        this.modeName = modeName;
        this.operationType = operationType;
        this.operationDesc = operationDesc;
        this.operatorId = operatorId;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbggenerated
     */
    public OptLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.id
     *
     * @return the value of opt_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.id
     *
     * @param id the value for opt_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.supplier_id
     *
     * @return the value of opt_log.supplier_id
     *
     * @mbggenerated
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.supplier_id
     *
     * @param supplierId the value for opt_log.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.mode_name
     *
     * @return the value of opt_log.mode_name
     *
     * @mbggenerated
     */
    public String getModeName() {
        return modeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.mode_name
     *
     * @param modeName the value for opt_log.mode_name
     *
     * @mbggenerated
     */
    public void setModeName(String modeName) {
        this.modeName = modeName == null ? null : modeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.operation_type
     *
     * @return the value of opt_log.operation_type
     *
     * @mbggenerated
     */
    public Byte getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.operation_type
     *
     * @param operationType the value for opt_log.operation_type
     *
     * @mbggenerated
     */
    public void setOperationType(Byte operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.operation_desc
     *
     * @return the value of opt_log.operation_desc
     *
     * @mbggenerated
     */
    public String getOperationDesc() {
        return operationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.operation_desc
     *
     * @param operationDesc the value for opt_log.operation_desc
     *
     * @mbggenerated
     */
    public void setOperationDesc(String operationDesc) {
        this.operationDesc = operationDesc == null ? null : operationDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.operator_id
     *
     * @return the value of opt_log.operator_id
     *
     * @mbggenerated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.operator_id
     *
     * @param operatorId the value for opt_log.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_log.create_time
     *
     * @return the value of opt_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_log.create_time
     *
     * @param createTime the value for opt_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}