package com.xinchao.entrytask.bus.dao;

import com.xinchao.entrytask.bus.model.CodeHelp;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface CodeHelpMapper {

    @Select(value = "select id,problem,enabled,sort from code_help where enabled='1' order by sort asc")
    List<CodeHelp> get();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help
     *
     * @mbggenerated
     */
    int insert(CodeHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help
     *
     * @mbggenerated
     */
    int insertSelective(CodeHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help
     *
     * @mbggenerated
     */
    CodeHelp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CodeHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CodeHelp record);
}