package com.xinchao.entrytask.bus.dao;

import com.xinchao.entrytask.bus.model.CodeHelpAnswer;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface CodeHelpAnswerMapper {

    @Select(value = "select id,problem_id problemId,answer,enabled,sort from code_help_answer where problem_id=#{problemId} and enabled='1' order by sort asc")
    List<CodeHelpAnswer> get(Long problemId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help_answer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help_answer
     *
     * @mbggenerated
     */
    int insert(CodeHelpAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help_answer
     *
     * @mbggenerated
     */
    int insertSelective(CodeHelpAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help_answer
     *
     * @mbggenerated
     */
    CodeHelpAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help_answer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CodeHelpAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_help_answer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CodeHelpAnswer record);
}