package com.xinchao.entrytask.bus.dao;

import com.xinchao.entrytask.bus.model.OptLog;
import com.xinchao.entrytask.bus.model.OptLogCondition;

import java.util.List;

public interface OptLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbggenerated
     */
    int insert(OptLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbggenerated
     */
    int insertSelective(OptLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbggenerated
     */
    OptLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OptLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OptLog record);

    int selectCount(OptLogCondition condition);

    List<OptLog> selectByCondition(OptLogCondition condition);
}