package com.xinchao.entrytask.bus.dao;

import com.xinchao.entrytask.bus.model.SaleArea;

import java.util.List;

public interface SaleAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_area
     *
     * @mbggenerated
     */
    int insert(SaleArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_area
     *
     * @mbggenerated
     */
    int insertSelective(SaleArea record);

    List<SaleArea> selectByCondition(SaleArea saleArea);

    SaleArea selectByCityName(String cityName);

}